### ISSUE TITLE
a few concerns

### ISSUE THREAD

**Issue by rhett-web** [ElemeFE/random#1]
1、当输入非数字时，没有message提示
      if(!size) return;    

2、如果team里female较少(一般情况)，不能正确分组了
      return females.map(function(group, i) {
        return group.concat(males[i] || []);
      });
      //这是要求每个group里都必须有妹子吗？
      //26个member，4个妹子，想分6组

![random](https://cloud.githubusercontent.com/assets/13705806/11180304/a2a9c464-8c94-11e5-8ebf-9a60a7cc872e.png)

**Comment by sofish** [comment]
- 第一个问题，不提醒是对的，你可以试试。
- 第二个问题，这是一个 bug :+1: 

多谢，这么久才看到 :laughing:

**Comment by rhett-web** [comment]
my pleasure，大神 😁😁😍😍
